Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2020-11, with the labels that each got.

#107 VPC Power states
  .rubocop_local.yml
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
  spec/factories/vm_or_template.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm_spec.rb
Labels: enhancement, kasparov/yes?

#113 Operating system mapping updates
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: bug, kasparov/yes?

#117 avoiding errors if os_name is nil, and if region has no description.
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
Labels: kasparov/yes?

#84 Declared DDF schema for cloud volume creation and editing
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: enhancement, wip

#114 Set the supports :auth_key_pair_create on the CloudManager
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
Labels: enhancement, kasparov/no

#119 Drop gettext initializer
  config/initializers/gettext.rb
Labels: cleanup

#118 Added SecurityGroup class that was missing from IBM Cloud Provider power
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager/security_group.rb
Labels: bug

#115 Refactor vm_or_template operating_system builder
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
Labels: refactoring

#120 Catch api key auth error.
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
Labels: bug, kasparov/yes?

#121 Append attached to status string if attached to vm.
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
Labels: enhancement
