Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2020-08, with the labels that each got.

#2 Fix typo in badge
  README.md
Labels: bug

#3 Use rubocop-0-69 for codeclimate
  .codeclimate.yml
Labels: developer

#7 The ems_type is supposed to be singular
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
Labels: bug

#6 Delete unused metrics_collector_worker/metrics_capture
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/metrics_collector_worker/runner.rb
  config/settings.yml
Labels: technical debt

#9 Update PowerVirtualServers::CloudManager descripton
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
Labels: bug
