Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2020-09, with the labels that each got.

#12 Ensure_managers_zone wasn't being called on update
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
Labels: bug

#13 Fix volume size
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
Labels: bug

#14 Fix instance hardware disk values
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: bug

#10 Add VM spec
  spec/factories/vm.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm_spec.rb
Labels: test

#16 Remove duplicate method 'networks'
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
Labels: cleanup

#17 Cleanup Template#provider_object method
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
Labels: cleanup

#20 Fix vcr specs for rest-client 2.1.0
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: test

#21 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer

#24 Remove stale volume API calls module
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/vol_api_calls.rb
Labels: cleanup

#27 Added VMI deletion support
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
Labels: enhancement

#32 Add credential validation to the provider form
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
Labels: enhancement

#29 Initial addition of IBM provider.
  app/models/manageiq/providers/ibm_cloud/inventory/collector.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/template.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager.yml
Labels: enhancement

#36 Fix PowerVS ems connect options (use ':service' instead of ':target')
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/auth_key_pair.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
Labels: bug

#35 Fix PowerVS delete subnet call
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager/cloud_subnet.rb
Labels: bug

#34 Implement PowerVS CloudVolume delete
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: enhancement

#37 Remove redundant braces around connect options
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
Labels: cleanup

#30 Changes to add the system & storage type collection information to a cloud instance
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/storage_type.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/system_type.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: enhancement

#40 Remove explicit region context from PowerVS Collector
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: refactoring

#41 Added Network Manager. More discovery, linking and specs.
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_network.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_subnet.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/security_group.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: enhancement

#43 Refactor VPC::CloudManager::Refresher Spec
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: bug, test

#45 Extend the bearer token expiration until 2100-01-01
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: bug, test

#44 Set PowerVS SystemType name
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
Labels: enhancement

#42 Add power state mapping
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: enhancement

#46 Collect assigned virtual cores for PowerVS Instances
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
Labels: enhancement

#50 PowerVS: Use 'cloud_volume_types' table for storage types
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/storage_type.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume_type.rb
Labels: enhancement

#52 Setting default subnet type to 'vlan-pub' in PVS
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
Labels: refactoring

#51 Make the default credentials required in the provider DDF
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
Labels: bug

#53 Add PowerVS Cloud Volume Create
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: enhancement

#55 Enable manageiq-provider-ibm_cloud logging
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  config/settings.yml
Labels: enhancement

#59 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
Labels: enhancement
