Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2020-10, with the labels that each got.

#54 Initial storage function for IBM Cloud Provider
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: enhancement

#67 PowerVS: Remove storage type collector
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: enhancement

#65 PowerVS: Add Availability Zone
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers.rb
Labels: enhancement

#70 PowerVS: Enable Cloud Volume attach and detach
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: enhancement

#69 discovering/linking NICs. Need sdk pr to link to floating ips
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: enhancement

#66 Enabled hard and soft reset to the VM instance
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm_spec.rb
Labels: enhancement

#58 Bound cloud storage types on PVS prov. to API returned values
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
Labels: enhancement

#47 Added support for Cloud Volume creation in IBM PVS provisioning
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/state_machine.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  content/miq_dialogs/miq_provision_ibm_dialogs_template.yaml
  spec/factories/vm_or_template.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow_spec.rb
Labels: enhancement

#74 PowerVS cleanup
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/state_machine.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager/cloud_network.rb
  config/settings.yml
Labels: cleanup

#79 Raise user friendly registration exceptions
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
Labels: enhancement

#77 Update PowerVS cloud subnet parser
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
Labels: enhancement

#80 adding bitness, and linking security groups to instances
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: enhancement

#81 Automatically replace the Bearer auth expiration timestamp
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: technical debt, test

#85 Set Cloud Volume 'multi-attachment' column
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
Labels: enhancement

#83 Fix VPC CloudManager verify_credentials
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager.yml
Labels: bug

#22 Add PowerVS CloudVolume Spec
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
  spec/factories/cloud_volume.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume_spec.rb
Labels: test

#76 Link Storage and Availability Zone in VPC
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: enhancement

#86 Filter existing volume types in provisioning form
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
Labels: enhancement

#88 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#78 Add VM provisioning checkbox for public network
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/state_machine.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  content/miq_dialogs/miq_provision_ibm_dialogs_template.yaml
Labels: enhancement

#90 Apply gettext for string internationalization
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: internationalization

#89 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-ibm_cloud.gemspec
Labels: developer, enhancement

#105 Use consistent child manager names
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
Labels: bug

#110 adding automatic refresh for ibm vpc
  config/settings.yml
Labels: bug, kasparov/yes?

#111 Added NetworkRouter class that was missing from IBM Cloud Provider
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/network_router.rb
Labels: bug

#112 Add PowerVS NetworkRouter class
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager/network_router.rb
Labels: bug, kasparov/yes?
