Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-06, with the labels that each got.

#217 Added Delete VM Functionality for VPC
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/sdk/branch.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/vpc_sdk/instance.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm_spec.rb
Labels: enhancement

#218 VPC Targeted Refresh for VMs
  app/models/manageiq/providers/ibm_cloud/inventory.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc/target_collection.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc/target_collection.rb
  config/settings.yml
Labels: enhancement

#220 Remove unused validate_reboot method
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm_spec.rb
Labels: technical debt

#221 VPC Targeted Refresh Support for Images and Flavors
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
Labels: enhancement

#222 Targeted Refresh Support for Various Resources
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
Labels: enhancement

#223 Add VM Targeted refresh specs
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher/vm_target.yml
Labels: test

#225 Exception handling for VM targeted refresh
  app/models/manageiq/providers/ibm_cloud/inventory.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: enhancement

#224 Targeted Refresh Support for Auth Keys, Floating IPs, and Volume Types
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
Labels: enhancement

#219 Make the target_collection class name more generic
  app/models/manageiq/providers/ibm_cloud/inventory.rb
Labels: refactoring

#226 Storage managers shouldn't delegate zone to parent_manager
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager.rb
Labels: bug

#159 Adding new IBM Cloud-Object-Storage provider
  .gitignore
  app/models/manageiq/providers/ibm_cloud/inventory/collector.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/object_storage.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/object_storage/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/object_storage.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/object_storage/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/object_storage.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/object_storage/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/object_storage/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/object_storage/storage_manager/refresh_worker.rb
  app/models/manageiq/providers/ibm_cloud/object_storage/storage_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/ibm_cloud/object_storage/storage_manager/refresher.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager/security_group.rb
  config/secrets.defaults.yml
  config/settings.yml
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/ibm_cloud/object_storage/storage_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_cloud/object_storage/storage_manager_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/object_storage/storage_manager/refresher.yml
  systemd/manageiq-providers-ibm_cloud_object_storage_storage_manager_refresh.target
  systemd/manageiq-providers-ibm_cloud_object_storage_storage_manager_refresh@.service
Labels: enhancement

#227 VPC Delete cloud networks functionality
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_network.rb
  spec/factories/cloud_network.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_network_spec.rb
Labels: enhancement, unmergeable

#229 Simplify VCR refresher spec by not duplicating ems
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: technical debt, test

#232 VPC delete cloud subnets functionality
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager/cloud_subnet.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_subnet.rb
  spec/factories/cloud_subnet.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_subnet_spec.rb
Labels: enhancement

#230 Fix missing VPC Flavor subclass
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/flavor.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: bug

#231 Fix tenant_id method conflicting with the column
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/auth_key_pair.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
Labels: bug, lasker/yes?

#235 Refactor create cloud subnet queue
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
Labels: refactoring
