Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-10, with the labels that each got.

#289 [MORPHY] Fix instance provision workflow
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision/payload.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb
Labels: bug

#291 Update 'ibm_cloud_power' gem
  manageiq-providers-ibm_cloud.gemspec
Labels: bug, morphy/yes?

#287 Convert AuthKey operations to SupportsFeatureMixin
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/auth_key_pair.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/auth_key_pair_spec.rb
Labels: technical debt

#286 VPC Rake task for refresh setup
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
  lib/tasks_private/vpc.rake
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher/vm_target.yml
Labels: developer, test
