Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-08, with the labels that each got.

#249 disabling warning dialog on redirect from image import form
  app/javascript/components/import-image-form/import-image-form.jsx
Labels: enhancement

#247 Image Import Dispatcher for IBM Cloud
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow/import_dispatcher.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
Labels: enhancement

#251 Power Virtual Machine specific reports
  content/reports/1000_IBM Power - Virtual Machines/010_PVMs_ Hardware.yaml
  content/reports/1000_IBM Power - Virtual Machines/011_PVMs_ Hardware.yaml
  content/reports/1000_IBM Power - Virtual Machines/012_PVMs_ Hardware.yaml
Labels: enhancement

#254 Initial IBM Cloud Databases support
  app/models/manageiq/providers/ibm_cloud/database_types.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/cloud_database.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/cloud_database_flavor.rb
  db/fixtures/ibm_cloud_database_types.yml
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: enhancement

#253 Validator task for a PowerVC node in PVC <-- PVS import workflow
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
  content/ansible_runner/roles/image-copy-pvc-to-pvs/files/sample.txt
  content/ansible_runner/roles/image-copy-pvc-to-pvs/files/upload_ova_to_bucket.py
  content/ansible_runner/roles/image-copy-pvc-to-pvs/tasks/execute.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/tasks/main.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/tasks/validate.yml
  content/ansible_runner/run.yml
Labels: enhancement

#255 Add supports :storage_manager and block_storage_manager function to IBM Cloud
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
Labels: enhancement

#256 Fix PowerVS image collector to handle elusive image IDs
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
Labels: bug

#259 VPC event targeted refresh for VMs
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_catcher/stream.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_parser.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_target_parser.rb
  config/settings.yml
Labels: enhancement

#265 Refactor SDK connections
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_catcher/stream.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_network.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_subnet.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_network_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_subnet_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume_spec.rb
Labels: refactoring

#250 PowerVS Targeted Refresh
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers/target_collection.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers/target_collection.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers/target_collection.rb
  config/settings.yml
Labels: enhancement

#262 Additional support for IBM Cloud Databases
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
  db/fixtures/ibm_cloud_database_types.yml
  lib/manageiq/providers/ibm_cloud/cloud_tool.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/cloud_databases.rb
  manageiq-providers-ibm_cloud.gemspec
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: enhancement
