Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-02, with the labels that each got.

#132 corrections for creating PCloudTenantsSSHKeysApi used by ibm-cloud-sdk-ruby::pcloud_tenants_sshkeys_post
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/auth_key_pair.rb
Labels: bug

#136 Fix PowerVS system_pools (flavors) parser
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
Labels: bug

#139 Powervs SAP provisioning
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/options_helper.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/sap_profile.rb
  content/miq_dialogs/miq_provision_ibm_dialogs_template.yaml
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: enhancement

#138 Convert `supports_#{op}?` to `supports?(op)`
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager_spec.rb
Labels: refactoring

#141 Adjust empty/initial values for select fields in DDF schemas
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
Labels: enhancement

#143 Fix PowerVS API endpoint special cases
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  config/settings.yml
Labels: bug

#142 Rubocop warns about Unnecessary disabling of cops
  .rubocop_local.yml
  lib/manageiq/providers/ibm_cloud/cloud_tools/common/proxy.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/taggings.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/vpc.rb
Labels: cleanup

#140 Implemented DDF for cloud subnets and added support mixin call
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager/cloud_subnet.rb
Labels: enhancement

#145 Don't require cloud_tools in lib/manageiq-providers-ibm_cloud.rb
  lib/manageiq-providers-ibm_cloud.rb
Labels: bug
