Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-11, with the labels that each got.

#300 Add resize VM functionality
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/vpc_sdk/instance.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: enhancement

#304 Fix VPC event catch poll sequence
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_catcher/stream.rb
Labels: bug

#305 Add resource group exception for refresh
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
Labels: bug, morphy/yes?

#307 Use the Regions class support from core
  app/models/manageiq/providers/ibm_cloud/vpc/regions.rb
  config/settings.yml
  config/vpc_regions.yml
Labels: refactoring
