Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-04, with the labels that each got.

#181 Changes in the volume_params so the volume can be created correctly
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: bug, lasker/yes?

#182 Pluggable provider secrets
  config/secrets.defaults.yml
  lib/manageiq/providers/ibm_cloud/engine.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_tools_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/VPC_can_get_a_response.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/VPC_can_paginate.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/can_get_a_Tagging_client.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/can_get_a_VPC_client.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/Can_get_generic_new_auth_using_api_key_only.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/Can_get_generic_new_auth_using_expired_bearer_info_and_api_key_.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/Can_get_generic_new_auth_using_expired_bearer_info_and_provided_api_key_.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/iam_auth.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: refactoring, test

#183 Do not memoize selected sap profile
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
Labels: bug, lasker/yes?

#185 Updates for v2.0 of ibm_cloud_resource_controller
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  manageiq-providers-ibm_cloud.gemspec
Labels: dependencies

#184 Remove default 'Network Interfaces' selection
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  content/miq_dialogs/miq_provision_ibm_dialogs_template.yaml
Labels: bug, kasparov/yes?, lasker/yes?

#188 New volume parameter should use 'disk_type'
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow_spec.rb
Labels: bug, lasker/yes?

#187 Use consistent value types for 'affinity_policy'
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: bug, lasker/yes?

#189 Cloud tool authentication
  lib/manageiq/providers/ibm_cloud/cloud_tools/authentication.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/common/timeout.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_tools_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/can_get_a_Tagging_client.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/can_get_a_VPC_client_with_expired_auth.yml
Labels: bug

#192 Fix SAP profile (flavor) memory units
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
Labels: bug, lasker/yes?

#196 [LASKER] Fix AvailabilityZone and Flavor duplication
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
Labels: bug

#193 Cloud tool resource manager
  lib/manageiq/providers/ibm_cloud/cloud_tool.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/authentication.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/resource_controller.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/resource_controller/common.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/resource_controller/controller.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/resource_controller/manager.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/sdk/branch.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_tools_spec.rb
  spec/vcr_cassettes/ManageIQ_Providers_IbmCloud_CloudTool/Can_get_resource_controller.yml
  spec/vcr_cassettes/ManageIQ_Providers_IbmCloud_CloudTool/Can_get_resource_manager.yml
Labels: enhancement

#195 Vpc inventory resource group
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/resource_group.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/ManageIQ_Providers_IbmCloud_VPC_CloudManager_Refresher/tests_the_refresh.yml
Labels: enhancement
