Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-12, with the labels that each got.

#308 VPC Metrics Capture
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/metrics_collector_worker/runner.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
  config/settings.yml
  manageiq-providers-ibm_cloud.gemspec
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/metrics_capture_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/metrics_capture.yml
  systemd/manageiq-providers-ibm_cloud_vpc_cloud_manager_metrics_collector.target
  systemd/manageiq-providers-ibm_cloud_vpc_cloud_manager_metrics_collector@.service
Labels: enhancement

#310 Remove secret from metrics VCR
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/metrics_capture.yml
Labels: test

#306 converting supported_for_create to supports :create
  app/models/manageiq/providers/ibm_cloud/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/object_storage/storage_manager.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager_spec.rb
Labels: refactoring

#312 converting supported_for_create to supports :create
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
Labels: refactoring
