Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-03, with the labels that each got.

#150 [KASPAROV] Allow API endpoint overrides through settings
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  config/settings.yml
Labels: bug

#151 Don't manually set the template's model_class
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
Labels: refactoring

#157 #156 Fix instance_actions issues with creating actions.
  lib/manageiq/providers/ibm_cloud/cloud_tools/vpc_sdk/instance.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/vpc_sdk/instance_actions.rb
Labels: bug, lasker/yes?

#152 Use the combined child-manager refresh support from core
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
Labels: refactoring

#153 Fix: Only get PowerVS SAP profiles if instance is 'sap' capable
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: bug, lasker/yes?

#160 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#168 Fix endpoint parsing for new PowerVS regions
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
Labels: bug, kasparov/conflict, kasparov/yes, lasker/yes

#169 [KASPAROV] Add api endpoints for new regions
  config/settings.yml
Labels: bug, kasparov/yes?

#131 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-ibm_cloud_power_virtual_servers_cloud_manager_refresh.target
  build/systemd_units/manageiq-providers-ibm_cloud_power_virtual_servers_cloud_manager_refresh@.service
  build/systemd_units/manageiq-providers-ibm_cloud_vpc_cloud_manager_refresh.target
  build/systemd_units/manageiq-providers-ibm_cloud_vpc_cloud_manager_refresh@.service
Labels: technical debt

#155 Provide method for CloudTool to authenticate with pre-fetched user_token.
  lib/manageiq/providers/ibm_cloud/cloud_tool.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/authentication.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/common/iam_auth.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_tools_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/VPC_can_get_a_response.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/VPC_can_paginate.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/can_get_a_Tagging_client.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/can_get_a_VPC_client.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/Can_get_generic_new_auth_using_api_key_only.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/Can_get_generic_new_auth_using_expired_bearer_info_and_api_key_.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/Can_get_generic_new_auth_using_expired_bearer_info_and_provided_api_key_.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/iam_auth.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloudtools/vpc_collection.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloudtools/vpc_response.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloudtools/vpc_token.yml
Labels: enhancement

#176 Add spec test for storage manager inventory
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
Labels: test

#179 VPC Add availability_zone relation to subnet.
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: enhancement

#178 Add ems_ref to auth_key_pairs
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: enhancement

#177 Use cloud volume types for volume profiles
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume_type.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: enhancement
