Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-07, with the labels that each got.

#236 VPC create cloud subnets functionality
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_subnet.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_subnet_spec.rb
Labels: enhancement

#238 VPC create cloud networks functionality
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_network.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_network_spec.rb
Labels: enhancement

#237 Collect cloud volume types
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  config/settings.yml
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: enhancement

#240 VPC delete cloud volumes functionality
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume.rb
  spec/factories/cloud_volume.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume_spec.rb
Labels: enhancement

#233 Rename Flavor CPU attributes
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: refactoring

#242 VPC create cloud volumes functionality
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume_spec.rb
Labels: enhancement

#245 Exception for image not found during refresh
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
Labels: bug, lasker/yes?

#241 Fix PowerVS VM 'cpu_type'
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: bug

#244 Set IBM Cloud specific vendor and icons
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/object_storage/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager.rb
  spec/factories/vm_or_template.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
Labels: technical debt

#215 Image Import Functionality for PowerVS <-- PowerVC scenario.
  app/helpers/manageiq/providers/ibm_cloud/toolbar_overrides/ems_cloud_center.rb
  app/javascript/components/import-image-form/import-image-form.jsx
  app/javascript/components/import-image-form/import-image-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/models/manageiq/providers/ibm_cloud/object_storage/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  content/ansible_runner/import.yaml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/.travis.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/README.md
  content/ansible_runner/roles/image-copy-pvc-to-pvs/defaults/main.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/files/upload_ova_to_bucket.py
  content/ansible_runner/roles/image-copy-pvc-to-pvs/handlers/main.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/meta/main.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/secrets.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/tasks/main.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/templates/credentials.aes
  content/ansible_runner/roles/image-copy-pvc-to-pvs/tests/inventory
  content/ansible_runner/roles/image-copy-pvc-to-pvs/tests/test.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/vars/main.yml
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/ibm_cloud/object_storage/storage_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_cloud/object_storage/storage_manager_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/object_storage/object_manager/refresher.yml
Labels: enhancement

#246 Added two additional Advanced Settings
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: enhancement

#248 IBM Cloud event collection
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_catcher/runner.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_catcher/stream.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
  config/settings.yml
  lib/manageiq/providers/ibm_cloud/cloud_tool.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/activity_tracker.rb
  manageiq-providers-ibm_cloud.gemspec
  systemd/manageiq-providers-ibm_cloud_vpc_cloud_manager_event_catcher.target
  systemd/manageiq-providers-ibm_cloud_vpc_cloud_manager_event_catcher@.service
Labels: enhancement
