Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-09, with the labels that each got.

#268 [MORPHY] Use cloud volume types for volume profiles
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/vpc.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume_type.rb
  lib/manageiq/providers/ibm_cloud/cloud_tool.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/authentication.rb
  lib/manageiq/providers/ibm_cloud/cloud_tools/common/iam_auth.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_tools_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/VPC_can_get_a_response.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/VPC_can_paginate.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/can_get_a_Tagging_client.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tool/can_get_a_VPC_client.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/Can_get_generic_new_auth_using_api_key_only.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/Can_get_generic_new_auth_using_expired_bearer_info_and_api_key_.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/Can_get_generic_new_auth_using_expired_bearer_info_and_provided_api_key_.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloud_tools/authentication/iam_auth.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloudtools/vpc_collection.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloudtools/vpc_response.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/cloudtools/vpc_token.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: enhancement

#276 [MORPHY] Cloudtool verify method existence
  lib/manageiq/providers/ibm_cloud/cloud_tools/sdk/branch.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_tools_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/ManageIQ_Providers_IbmCloud_CloudTool/Raises_error_with_non-existent_method_.yml
Labels: enhancement

#277 [MORPHY] Exception handling for VM targeted refresh
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc/target_collection.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: enhancement

#278 [MORPHY] Simplify VCR refresher spec by not duplicating ems
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: technical debt, test

#272 Add support for IBM Cloud Kubernetes Service IKS
  app/models/manageiq/providers/ibm_cloud/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/container.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/container_group.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/container_node.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/event_catcher.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/event_catcher/runner.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/event_parser.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/refresh_worker.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/refresh_worker/watch_thread.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/refresher.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/container_manager/watch_notice.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/container_manager/watch_notice.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/container_manager/watch_notice.rb
  config/secrets.defaults.yml
  config/settings.yml
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/ibm_cloud/container_manager/refresher_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/container_manager/refresher.yml
  systemd/manageiq-providers-ibm_cloud_container_manager_event_catcher.target
  systemd/manageiq-providers-ibm_cloud_container_manager_event_catcher@.service
  systemd/manageiq-providers-ibm_cloud_container_manager_refresh.target
  systemd/manageiq-providers-ibm_cloud_container_manager_refresh@.service
Labels: enhancement

#281 remove exec bit from report yml files
  content/reports/1000_IBM Power - Virtual Machines/010_PVMs_ Hardware.yaml
  content/reports/1000_IBM Power - Virtual Machines/011_PVMs_ Hardware.yaml
  content/reports/1000_IBM Power - Virtual Machines/012_PVMs_ Hardware.yaml
Labels: technical debt

#282 Fix the settings_name for the IKS Refresh Worker
  app/models/manageiq/providers/ibm_cloud/container_manager/refresh_worker.rb
Labels: bug, morphy/yes?

#280 [MORPHY] Add support for IBM Cloud Kubernetes Service IKS
  app/models/manageiq/providers/ibm_cloud/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/container.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/container_group.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/container_node.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/event_catcher.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/event_catcher/runner.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/event_parser.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/refresh_worker.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/refresh_worker/watch_thread.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/refresher.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/collector/container_manager/watch_notice.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/container_manager/watch_notice.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/container_manager/watch_notice.rb
  config/secrets.defaults.yml
  config/settings.yml
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/ibm_cloud/container_manager/refresher_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/container_manager/refresher.yml
  systemd/manageiq-providers-ibm_cloud_container_manager_event_catcher.target
  systemd/manageiq-providers-ibm_cloud_container_manager_event_catcher@.service
  systemd/manageiq-providers-ibm_cloud_container_manager_refresh.target
  systemd/manageiq-providers-ibm_cloud_container_manager_refresh@.service
Labels: enhancement

#283 New Reports for IBM Power
  content/reports/1000_IBM Power - Storage/010_PVMs_ Storage.yaml
  content/reports/1000_IBM Power - Storage/011_PVMs Storage.yaml
  content/reports/1000_IBM Power - Storage/012_PVMs Storage.yaml
  content/reports/1000_IBM Power - Virtual Machines/010_PVMs_ Hardware.yaml
  content/reports/1000_IBM Power - Virtual Machines/011_PVMs_ Hardware.yaml
  content/reports/1000_IBM Power - Virtual Machines/012_PVMs_ Hardware.yaml
Labels: enhancement

#284 Add PowerVS VM creation date to inventory
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
Labels: enhancement

#260 Convert cloud volume operations to SupportsFeatureMixin
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume_spec.rb
Labels: technical debt
