Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2021-05, with the labels that each got.

#200 Floating ip to instance
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/ManageIQ_Providers_IbmCloud_VPC_CloudManager_Refresher/tests_the_refresh.yml
Labels: enhancement

#202 Fix the dynamic secret cassette placeholder code
  spec/spec_helper.rb
Labels: bug, test

#198 Vpc provision
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/logging_mixin.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision/payload.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision/state_machine.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/common.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/fields.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/hardware.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/network.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/volumes.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/template.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm_or_template_shared.rb
  content/miq_dialogs/miq_provision_vpc_dialogs.yaml
Labels: enhancement

#207 [LASKER] Collector.image was using wrong method.
  app/models/manageiq/providers/ibm_cloud/inventory/collector/vpc.rb
Labels: bug

#208 Cloudtool verify method existence
  lib/manageiq/providers/ibm_cloud/cloud_tools/sdk/branch.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_tools_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/ManageIQ_Providers_IbmCloud_CloudTool/Raises_error_with_non-existent_method_.yml
Labels: enhancement

#210 #209 remove resource_groups relation
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
Labels: enhancement

#212 Provision update rest
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/template.rb
Labels: enhancement

#211 Cloudtool instance tests
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_tools_spec.rb
  spec/vcr_cassettes/ManageIQ_Providers_IbmCloud_CloudTool/Instance_is_callable.yml
  spec/vcr_cassettes/ManageIQ_Providers_IbmCloud_CloudTool/Instances_is_callable.yml
Labels: enhancement

#216 [LASKER] Floating ip to instance
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher.yml
Labels: bug
