Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2022-10, with the labels that each got.

#422 Subclass Snapshot under PowerVirtualServers
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/snapshot.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
Labels: enhancement

#411 Remove placement groups from PowerVS advanced settings
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/placement_group.yml
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision.yml
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/snapshot.yml
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: enhancement

#426 removed placement group field from vm provision workflow
  content/miq_dialogs/miq_provision_ibm_powervs_dialogs_template.yaml
Labels: bug

#428 Upgrade workflows to actions/checkout@v3
  .github/workflows/ci.yaml
Labels: enhancement, test

#427 Add placement group option to powervs vm provisioning
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  content/miq_dialogs/miq_provision_ibm_powervs_dialogs_template.yaml
Labels: enhancement
