Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2022-03, with the labels that each got.

#339 passing COS sensitive info by id and adding RBAC enabled image-import button
  app/helpers/manageiq/providers/ibm_cloud/toolbar_overrides/ems_cloud_center.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow/image_import_button.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
Labels: bug, najdorf/yes?

#351 Fix IBM Cloud Activity Tracker gem
  lib/manageiq/providers/ibm_cloud/cloud_tools/activity_tracker.rb
  manageiq-providers-ibm_cloud.gemspec
Labels: bug, najdorf/yes?

#350 Saving volume type name as description as well for UI
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
Labels: bug, najdorf/yes?

#352 fix in IBM COS authentication validation
  app/models/manageiq/providers/ibm_cloud/object_storage/storage_manager.rb
Labels: bug, najdorf/yes?

#354 Add IBM Cloud Activity Tracker service key field for VPC
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
Labels: enhancement

#353 Affinity setting to drive fields on New Volume form
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: bug, najdorf/yes?

#355 Raise exception on volume deletion error
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: bug

#358 Fixed security_groups select bug
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision/payload.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/network.rb
  content/miq_dialogs/miq_provision_vpc_dialogs.yaml
Labels: bug

#359 [VPC] Add authentication validation for events
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
Labels: enhancement

#356 fix in the image import queuing mechanism
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow.rb
Labels: bug, najdorf/yes?

#362 Add support for VPC catalog provisioning
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/common.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/general.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/network.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/volumes.rb
  content/miq_dialogs/miq_provision_vpc_dialogs.yaml
Labels: enhancement
