Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2022-11, with the labels that each got.

#434 Fix AWS S3 VCR errors getting bucket location
  app/models/manageiq/providers/ibm_cloud/inventory/collector/object_storage.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/object_storage/storage_manager/refresher.yml
Labels: bug, test

#433 Remove VM resize support for SAP
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
Labels: bug, oparin/yes?

#437 Use postgresql:13 image for ci
  .github/workflows/ci.yaml
Labels: test

#439 Fix MetricsCollectorWorker running with invalid creds
  app/models/manageiq/providers/ibm_cloud/container_manager/metrics_collector_worker.rb
Labels: bug, oparin/yes?
