Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2022-01, with the labels that each got.

#315 Powervs event cleanup
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/event_parser.rb
Labels: enhancement

#319 Don't subclass ContainerVolume
  app/models/manageiq/providers/ibm_cloud/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/container_volume.rb
Labels: bug

#318 Move COS bucket logic into collector
  app/models/manageiq/providers/ibm_cloud/inventory/collector/object_storage.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/object_storage.rb
Labels: refactoring

#313 Adding Snapshots support for Inventory
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/persister/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: enhancement

#324 IKS Metrics Capture
  app/models/manageiq/providers/ibm_cloud/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/metrics_capture.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/metrics_capture/prometheus_capture_context.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/metrics_capture/prometheus_client.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/ibm_cloud/container_manager/metrics_collector_worker/runner.rb
  config/settings.yml
  manageiq-providers-ibm_cloud.gemspec
  systemd/manageiq-providers-ibm_cloud_container_manager_metrics_collector.target
  systemd/manageiq-providers-ibm_cloud_container_manager_metrics_collector@.service
Labels: enhancement

#326 Update PowerVS VM provision dialog name/description
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  content/miq_dialogs/miq_provision_ibm_powervs_vm_dialog.yaml
Labels: enhancement

#325 Hooking up Create Snapshot action to backend logic
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm/operations.rb
Labels: enhancement
