Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2022-05, with the labels that each got.

#375 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#373 rename CloudVolume#attach_volume to attach
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume_spec.rb
Labels: enhancement

#376 Add custom schema fields to IBM Cloud attach cloud volume form
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume.rb
Labels: enhancement

#361 Add specs for VPC provision workflow
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow/common.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow_spec.rb
Labels: test

#378 inheriting impage import job and dispatcher from base
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow/import_dispatcher.rb
Labels: najdorf/yes?

#379 Fix powervs vm provision ipv4 field
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  content/miq_dialogs/miq_provision_ibm_powervs_vm_dialog.yaml
Labels: bug

#383 remove ssh public key
  lib/tasks_private/terraform/id_rsa.pub
Labels: bug

#385 Add spec to show network_manager.refresh failure
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/refresher_spec.rb
Labels: bug
