Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2022-02, with the labels that each got.

#330 Remove Hakiri
  README.md
Labels: developer, test

#327 Wiring delete a snapshot & all snapshots to backend
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm/operations.rb
Labels: enhancement

#331 Hooking up Snapshot restore action to backend
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm/operations.rb
Labels: enhancement

#332 Calculate snapshot size by tallying up associated volume sizes
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
Labels: enhancement

#329 new terraformed scripts for test automation
  .gitignore
  config/powervs_testsettings.yml
  config/secrets.defaults.yml
  lib/tasks_private/terraform/README.md
  lib/tasks_private/terraform/id_rsa.pub
  lib/tasks_private/terraform/main.tf
  lib/tasks_private/terraform/outputs.tf
  lib/tasks_private/terraform/provider.tf
  lib/tasks_private/terraform/provision.rake
  lib/tasks_private/terraform/variables.tf
  lib/tasks_private/terraform/version.tf
  manageiq-providers-ibm_cloud.gemspec
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision-vm.yml
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher.yml
Labels: enhancement, test

#336 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-ibm_cloud.gemspec
Labels: developer, test

#334 Fixed the cloud volume add form
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume.rb
Labels: bug

#335 PowerVS additional events
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/event_parser.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/event_target_parser.rb
  config/settings.yml
Labels: enhancement

#340 updated the vm naming convention to what is defined for PowerVS. Also…
  content/miq_dialogs/miq_provision_ibm_powervs_vm_dialog.yaml
Labels: bug, morphy/yes?

#341 Powervs catalog provisioning
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  content/miq_dialogs/miq_provision_ibm_powervs_vm_dialog.yaml
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager_spec.rb
Labels: enhancement

#344 Add Build History Graph to README.md
  README.md
Labels: developer, test

#338 disabling SSH pw auth for image import
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow/ssh_pkey_credential.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
Labels: bug

#337 rcfile location fix and ansible role dir. cleanup
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
  content/ansible_runner/roles/image-copy-pvc-to-pvs/.travis.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/README.md
  content/ansible_runner/roles/image-copy-pvc-to-pvs/defaults/main.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/handlers/main.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/meta/main.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/secrets.yml
  content/ansible_runner/roles/image-copy-pvc-to-pvs/tests/inventory
  content/ansible_runner/roles/image-copy-pvc-to-pvs/tests/test.yml
Labels: bug

#347 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
