Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2022-08, with the labels that each got.

#401 Filtering the storage disk type by destination provider in import form.
  app/javascript/components/import-image-form/import-image-form.jsx
Labels: enhancement

#405 Import Image Form changes to take COS
  app/javascript/components/import-image-form/import-image-form.jsx
  app/javascript/components/import-image-form/import-image-form.schema.js
Labels: unmergeable

#406 IBM Cloud Power SDK updates
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/image_import_workflow.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
  config/settings.yml
  manageiq-providers-ibm_cloud.gemspec
Labels: enhancement

#413 Replace persister.cloud_volumes.find with .lazy_find
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
Labels: bug

#407 Update PowerVS cloud volume create with affinity controls
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
Labels: enhancement

#414 Use supports instead of availability for Template#delete_image
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm_spec.rb
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm_spec.rb
Labels: technical debt

#415 Consolidate and rename PowerVS provisioning dialogs
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision_workflow.rb
  content/miq_dialogs/miq_provision_ibm_powervs_dialogs_clone_to_template.yaml
  content/miq_dialogs/miq_provision_ibm_powervs_dialogs_template.yaml
  content/miq_dialogs/miq_provision_ibm_powervs_vm_dialog.yaml
Labels: bug, oparin/yes?

#417 Fix deprecated `Module#parent` in EventCatcher
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/event_catcher/runner.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/event_catcher/runner.rb
Labels: bug, oparin/yes?
