Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2022-07, with the labels that each got.

#402 Improve IAM auth error message
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
Labels: enhancement

#404 Fix start_clone IbmCloudPower::ApiError rescue
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
Labels: bug, najdorf/yes?

#408 Removing memoization
  app/models/manageiq/providers/ibm_cloud/object_storage/storage_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/manager_mixin.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
Labels: bug

#409 Fix PowerVS inventory refresh when volumes are missing
  app/models/manageiq/providers/ibm_cloud/inventory/collector/power_virtual_servers.rb
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
Labels: bug
