Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2023-06, with the labels that each got.

#455 PowerVS Cloning: Use ems_ref, not name, to find new VM or Template
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
Labels: bug

#460 Retirement settings upon VM provision in PowerVS
  content/miq_dialogs/miq_provision_ibm_powervs_dialogs_template.yaml
Labels: enhancement

#461 Fix missing System Profile dropdown VPC Provision
  content/miq_dialogs/miq_provision_ibm_vpc_dialogs_template.yaml
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/provision_workflow_spec.rb
Labels: bug, petrosian/yes?

#462 PowerVS: Attach newly created volumes during VM provision
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/state_machine.rb
Labels: bug

#463 Fix clone_to_template provision preparation
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/provision/state_machine.rb
Labels: bug
