Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2023-10, with the labels that each got.

#473 Bump all ibm_cloud/ibm_vpc gems for http 5.1 to resolve known HTTP::ConnectionError issues
  manageiq-providers-ibm_cloud.gemspec
Labels: bug, quinteros/yes?

#474 Use new resource pool cpu_core_* columns
  app/models/manageiq/providers/ibm_cloud/inventory/parser/power_virtual_servers.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
Labels: enhancement

#475 Handle VPC flavor with nil :disks value
  app/models/manageiq/providers/ibm_cloud/inventory/parser/vpc.rb
Labels: bug

#476 Update GitHub CODEOWNERS
  .github/CODEOWNERS
Labels: developer

#477 Drop Ruby 2.7
  .github/workflows/ci.yaml
Labels: dependencies
