Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2024-02, with the labels that each got.

#483 Fix duplicate advanced settings
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager.rb
  spec/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/refresher_spec.rb
Labels: bug, quinteros/yes?

#484 Add new VPC regions
  config/vpc_regions.yml
  spec/models/manageiq/providers/ibm_cloud/vpc/cloud_manager_spec.rb
Labels: enhancement, quinteros/yes?

#485 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#486 drop use of unsupported_reason_add an supports_feature
  app/models/manageiq/providers/ibm_cloud/container_manager.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/template.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/network_manager/cloud_subnet.rb
  app/models/manageiq/providers/ibm_cloud/power_virtual_servers/storage_manager/cloud_volume.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/template.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/vm.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_network.rb
  app/models/manageiq/providers/ibm_cloud/vpc/network_manager/cloud_subnet.rb
  app/models/manageiq/providers/ibm_cloud/vpc/storage_manager/cloud_volume.rb
Labels: refactoring

#487 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
