Repository ManageIQ/manageiq-providers-ibm_cloud, pull requests merged in 2025-05, with the labels that each got.

#523 Fix metrics endpoint DDF Form
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager.rb
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/ibm_cloud/vpc/manager_mixin.rb
Labels: bug, spassky/yes?

#526 Fix uninitialized constant IBMCloudSdkCore
  app/models/manageiq/providers/ibm_cloud/vpc/cloud_manager/metrics_capture.rb
Labels: bug, spassky/yes?

#520 Add schedule tab with "Time until Retirement"
  content/miq_dialogs/miq_provision_ibm_vpc_dialogs_template.yaml
Labels: enhancement

#521 Update minimum node version to 20.19.1
  package.json
Labels: dependencies

#528 Drop build stats since buildstats.info is dead
  README.md
Labels: technical debt
